/*
  Question :  There are six processes in this problem: five student processes and an
              agent process. Each of the student processes will make a computer and use it. To make
              a computer requires CPU, monitor, keyboard, mouse and the connecting wires. Each
              student process has one of the five items. i.e., one process has CPU, another has
              monitor, third has keyboard and so on. The agent has an infinite supply of all five
              items and each student has also infinite supply of his own item. The agent places four
              of the five items on the table, and the student who has the remained fifth item makes
              the computer and use it. Synchronize the processes.
*/

#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<pthread.h>
#include<semaphore.h> 
#include<unistd.h> 
#include<time.h>

char* arr[] = {"CPU","monitor","keyboard","mouse","wires"}; 
int generated_items[5]; // that index value is 1 which the agent has already generated 
int table_used = 1; // value 1 if table is free to use
int generated = 0; //value 0 if agent is yet to generate 4 random items

sem_t table; //binary semaphore to lock table when being used by agent.

void *agent1(void * args)
{
	int r1;

	while(1)
	{
		sleep(1);
		if(table_used==1)
		{
			sem_wait(&table); //agent locks table for use

			for(int i=0;i<5;i++)
			{
				generated_items[i] = 0; 
			}

			r1 = rand() % 5 + 1; //random number in the range [1,5]

			printf("Random number is %d\n",r1);

			for(int i=0;i<5;i++)
			{
				generated_items[i] = 1;           
			}
			generated_items[r1-1] = 0;      // for that item which agent has not generated


			printf("Items generated by the agent are :");
			for(int i=0;i<5;i++)
			{
				if(generated_items[i]==1)
				printf("%s\n",arr[i]);
			}
			generated = 1;
			table_used = 0;
		}

			sem_post(&table);  //agent releases lock from table

	}	
	
}

void *student(void * args)
{
	int p = (int *)args;
	//printf("p is %d\n",p);
	//int p1=(*p);
	while(1)
	{
		sleep(1);
		sem_wait(&table); //table locked by student
		if(table_used==0)
		{
				//printf("P is %d\n",p);
        
        //student checks if the item he owns has been generated by the agent or not
				if(generated && generated_items[p-1]==0)
				{
					printf("Student %d is done with it!\n",p);
					table_used = 1;
					generated = 0;
				}
				
		}

		sem_post(&table); // table ready for use by agent
	}
	
}

int main()
{

	pthread_t s1,s2,s3,s4,s5,agent; // six threads for six processes
	
	sem_init(&table,0,1);
	pthread_create(&agent,0,agent1,(void*)0);
	pthread_create(&s1,0,student,(void*)1);
	pthread_create(&s2,0,student,(void*)2);
	pthread_create(&s3,0,student,(void*)3);
	pthread_create(&s4,0,student,(void*)4);
	pthread_create(&s5,0,student,(void*)5);
	while(1);
}
